version: '2'

services:
  ruby-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: yanhao/ruby-dev:2.5.0
    hostname: ruby.dev
    working_dir: /home/docker/src
    volumes:
      - ./src:/home/docker/src
      - ./config:/home/docker/.config
      - "${HOME}/.vbuf:/home/docker/.vbuf"
    volumes_from:
      - ssh-agent
    environment:
      - HISTFILE=/home/docker/.config/.zsh_history
      - DATABASE_URL=postgres://postgres:a@postgres
      - SSH_AUTH_SOCK=/.ssh-agent/proxy-socket
      - GIT_AUTHOR_NAME=Yanhao Yang
      - GIT_AUTHOR_EMAIL=me@example.com
      - GIT_COMMITTER_NAME=Yanhao Yang
      - GIT_COMMITTER_EMAIL=me@example.com

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: a

  ssh-agent:
    image: yanhao/ssh-agent

  ingress:
    image: openresty/openresty:1.13.6.2-alpine
    volumes:
      - .files/nginx:/etc/nginx
    ports:
      - "80:80"
