version: '2'

services:
  ruby-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: yanhao/ruby-dev:2.6.3
    hostname: ruby.dev
    working_dir: /home/docker/src
    volumes:
      - ./src:/home/docker/src
      - ./config:/home/docker/.config
      - "${HOME}/.vbuf:/home/docker/.vbuf"
    volumes_from:
      - ssh-agent
    environment:
      - HISTFILE=/home/docker/.config/.zsh_history
      - DATABASE_URL=postgres://postgres:a@postgres
      - SSH_AUTH_SOCK=/.ssh-agent/proxy-socket
      - GIT_AUTHOR_NAME=Yanhao Yang
      - GIT_AUTHOR_EMAIL=me@example.com
      - GIT_COMMITTER_NAME=Yanhao Yang
      - GIT_COMMITTER_EMAIL=me@example.com
    #labels:
      #- "traefik.frontend.rule=Host:ruby.localhost"
      #- "traefik.port=8000"

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: a

  ssh-agent:
    image: yanhao/ssh-agent

  ingress:
    image: traefik
    command: --api --docker --docker.domain=localhost
    ports:
      - "80:80"
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.frontend.rule=Host:dashboard.localhost"
      - "traefik.port=8080"
