#!/bin/bash

cd /usr/local/lib/ruby/gems/2.4.0/gems
ripper-tags --recursive

cd /usr/local/bundle/gems
ripper-tags --recursive

cd /usr/local/bundle/gems
ripper-tags --recursive --tag-file /home/docker/tags
